### ISSUE TITLE
index holes not electrons when numelec > nspf

### ISSUE THREAD

**Issue by djhaxton** [LBNL-AMO-MCTDHF/V1#22]
There will be memory and time savings if arrays like configlist(1:2*numelec,numconfig) are reindexed (1:2*numholes,numconfig) in cases -- which will be most cases when the number electrons numelec is large -- when numelec > nspf and therefore numholes < numelec because numelec + numholes = 2*nspf.

**Comment by danhax** [comment]
The speed up is not huge so far, but significant, maybe 2x faster for the benzene calculation I am trying, with about half as much memory.  Not sure that was worth it, but with v1.24 you can set holeflag=1 in namelist &parinp and keep track of your holes not electrons.  For hartree-fock it's a special case with no particles (a particle is a hole or an electron depending on holeflag) and no slater determinants; we just propagate a single coefficient that multiplies the vacuum (the closed shell).  Looks like it works.
